### ISSUE TITLE
Impossible to remove node if its container does not exist

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/flowbroker#103]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
It's not possible to remove a node if the container is not up

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Adds a new node to flowbroker
- Kills the node's container externally
- Tries to removes the node

* **What is the expected behavior?**
The node be removed

* **What is the motivation / use case for changing the behavior?**
The flowbroker enter in a dead state with this node, because it's not possible to add the node again once it exists in the database and we cannot remove it, due to this issue.

* **Please tell us about your environment:**
  
  - Version: 0.3.x (master on 30/01/2019)
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rascaraficci** [comment]
Done!
