### ISSUE TITLE
Remote node restart on bootstrap does not work with k8s

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/flowbroker#104]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
When the flowbroker restart and it has remote nodes, the node's containers are not started

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Add some remove node to flowbroker
- Shutdown the flowbroker
- Remove the node's container externally
- Start the flowbroker

* **What is the expected behavior?**
The node's container become up after the bootstrap phase

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.3.x (master on 30/01/2019)
  - Environment: kubernetes
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rascaraficci** [comment]
Duplicated
