### ISSUE TITLE
Remote nodes restart treatment is not correct

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/flowbroker#105]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
The remote node restart is not trusty

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Restart the flowbroker with some remote node added

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.3.x (master on 30/01/2019)
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Actually, the node restart uses the container stats to decide if should try to start a remote node container or not. There are several points that need to be reviewed on the remote node restart phase.

**Comment by rascaraficci** [comment]
Done!
