### ISSUE TITLE
How to enable logs on new node.

### ISSUE THREAD

**Issue by klossteles** [dojot/flowbroker#121]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**
Request a support.

* **What is the motivation / use case for changing the behavior?**

   I'am following the steps to add a new node (Kelvin) into dojot flowbroker (as it's on sample node tutorial). I managed to add it, but i want to change this node, so that i can see more logs of whats happening during the execution (docker-compose logs), like "Starting executing node Kelvin...", "...stopped executing node Kelvin". 
   Under flowbroker project directory (/flowbroker/orchestrator/nodes) I've found the default nodes provided with Dojot.

   Usually this logs are made using `logger.debug("Some log")`, I've tried to do as it's made on http and template node, but i can't get it to work. 
   Is there another way to do it? How am i supposed to add logs to a custom node? If it's possible, please provide the steps to it.

* **Please tell us about your environment:**
  
  - Version: 0.3.x or master
  - Environment: docker-compose
  - Operating system: Linux Mint 19.1 Cinnamon

Thanks.

**Comment by giovannicuriel** [comment]
Hi!

Did you try to get the logs directly from node container? 

In fact, remote nodes are kept separate from main flowbroker process - they run inside a container in a separate network. Just check which one you are interested with a `docker ps -a` and you should be able to get the logs by executing `docker logs -f DOCKER_NAME`. The name should be something like `flowbroker.adminkelvin.d744d1b`

**Comment by rascaraficci** [comment]
This issue will be closed due to inactivity.
