### ISSUE TITLE
"batch" node is needed

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/flowbroker#38]
It would be nice to have a node with similar functionality as the "batch" node from nodered - it will fire a message whenever X messages are received. This is specially interesting to add new nodes such as "calculate the mean value of this attribute" - which would be performed by, let's say, a "math" node.

**Comment by klossteles** [comment]
Hi @giovannicuriel!
Do you have any update on this topic? 
I really need something like that to Dojot work perfectly with my application.

**Comment by giovannicuriel** [comment]
Hi!

About this exact node there's nothing new. But we added a context manager to be used in remote nodes, which might be of your interest. You can save a chunk of data into a context and retrieve it whenever you need it while executing a node. 

Please, check [this file](https://github.com/dojot/flowbroker/blob/master/lib/ContextHandler.js) for more info.

**Comment by rascaraficci** [comment]
This issue will be closed due to inactivity
