### ISSUE TITLE
Unable to use multiple remote node types at dataflow GUI

### ISSUE THREAD

**Issue by fberanizo** [dojot/flowbroker#43]
When I add new node types using the endpoint "/flows/v1/node", other remote nodes disappear from dataflow GUI.

See nodeManager.js at line 137:
https://github.com/dojot/flowbroker/blob/655c07abbab3e8d33444989dae12256745a9f6a3/orchestrator/nodeManager.js#L137

Probably "this.remote" is undefined, and this.html is the same for all remote nodes.

**Comment by giovannicuriel** [comment]
Hi!

Yes, we were just checking this problem (as in dojot/dojot#489) and you are absolutely right - there is no "remote" attribute defined anywhere, so all HTML files for remote nodes are "/tmp/undefined".

Thank you so much for this!

**Comment by fberanizo** [comment]
Thanks! :)
