### ISSUE TITLE
Tenant should be informed when invoking remote nodes

### ISSUE THREAD

**Issue by fberanizo** [dojot/flowbroker#46]
Tenant is always undefined at handleMessage(config, message, callback, tenant) for remote nodes.

I'm not sure how to fix this. I guess it's something related to these lines of code:
https://github.com/dojot/flowbroker/blob/62490d221162f8903ff07991aaf50352973edac0/orchestrator/nodeManager.js#L172-L176

Att,

**Comment by raulnegreiros** [comment]
Hi @fberanizo, sorry the delay to answer. Nowadays this piece of information is not available to the handler, but this point was already addressed and soon we will add it.
As soon as it happens I will notify you.

**Comment by raulnegreiros** [comment]
Hi @fberanizo, the PR #50 added the parameter metadata to the handleMessage, you can find the tenant inside it among other things.

Could we close this issue?

**Comment by rascaraficci** [comment]
The reported problem was fixed.
